### ISSUE TITLE
What's up with IEnergyStorage?

### ISSUE THREAD

**Issue by vpzomtrrfrt** [NerdHubMC/Cardinal-Energy#1]
I see that you have an IEnergyStorage interface, and it looks like what I would expect to implement from my mod.  However, IEnergyHandler appears to only support the concrete EnergyStorage type.  Is this an oversight, or is there some reason getEnergyStorage doesn't return IEnergyStorage?

**Comment by alothmanmoe** [comment]
This was an accidental oversight, will fix it today, but the plan is also to allow for different "energy types" as well, i'll try to have an update out today if i can

**Comment by alothmanmoe** [comment]
This was fixed a long time ago, forgot to close
